### ISSUE TITLE
Webpage does not adhere to Design for universal accessability

### ISSUE THREAD

**Issue by Trondtr** [giellalt/giellalt.github.io#20]
To repeat: Install one of the browsers for the blind: Lynx (https://lynx.invisible-island.net/) or Links (http://links.twibright.com/), and open the giellalt.github.io page.

Most pages show very well, and we fare well compared to most webpages. But one feature is lost: The generated list do not survive into links. The important page **Language Models** shows everything -- except the list of language models.

**Comment by snomos** [comment]
[How to get Links with javascript support](https://stackoverflow.com/questions/61193617/how-to-enable-javascript-support-in-links).

In other words: the content is generated with javascript, and since javascript isn't supported by Lynx, the content vanishes. See the above link for a possible solution (but not for everyone), another solution is to prebuild the content on the server (but we are already approaching the time limit for building a GH Pages site, so it might break the whole thing).

The javascript used is simple, and I see no technical reason why Lynx and other text browsers could not support javascript. This is not an issue for us to solve, rather for those wanting to use text based browsers. This is also not an accessibility issue, screen readers will have no issue with parsing the web page as presented in a traditional GUI web browser.
